version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    hostname: mysql
    restart: always
    stdin_open: true

  api:
    container_name: api
    image: shibui/ml-system-in-actions:prediction_monitoring_pattern_api_0.0.1
    restart: always
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
      - MYSQL_SERVER=mysql
    entrypoint: ["./run.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  job:
    container_name: job
    image: shibui/ml-system-in-actions:prediction_monitoring_pattern_job_0.0.1
    entrypoint:
      [
        "python",
        "-m",
        "job.main",
        "--data_file",
        "job/rand_iris.csv",
        "--rate_per_second",
        "10",
        "--target_url",
        "http://api:8000/predict",
      ]
    restart: always
    depends_on:
      - api

  monitor:
    container_name: monitor
    image: shibui/ml-system-in-actions:prediction_monitoring_pattern_api_0.0.1
    entrypoint:
      [
        "python",
        "-m",
        "src.monitor.main",
        "--interval",
        "1",
        "--outlier_threshold",
        "0.2",
        "--average_sepal_length",
        "5.84",
        "--average_sepal_width",
        "3.06",
        "--average_petal_length",
        "3.76",
        "--average_petal_width",
        "1.20",
        "--threshold",
        "0.05",
      ]
    restart: always
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
      - MYSQL_SERVER=mysql
    depends_on:
      - api
