apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-svc
  namespace: load-test
  labels:
    app: iris-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-svc
  template:
    metadata:
      labels:
        app: iris-svc
    spec:
      containers:
        - name: iris-svc
          image: shibui/ml-system-in-actions:load_test_pattern_api_0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: "300Mi"
            requests:
              cpu: 500m
              memory: "300Mi"
          volumeMounts:
            - name: workdir
              mountPath: /workdir
          env:
            - name: MODEL_FILEPATH
              value: "/workdir/iris_svc.onnx"
            - name: WORKERS
              value: "8"
      initContainers:
        - name: model-loader
          image: shibui/ml-system-in-actions:load_test_pattern_loader_0.0.1
          imagePullPolicy: Always
          command:
            - python
            - "-m"
            - "src.main"
            - "--gcs_bucket"
            - "ml_system_model_repository"
            - "--gcs_model_blob"
            - "iris_svc.onnx"
            - "--model_filepath"
            - "/workdir/iris_svc.onnx"
          volumeMounts:
            - name: workdir
              mountPath: /workdir
      volumes:
        - name: workdir
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: iris-svc
  namespace: load-test
  labels:
    app: iris-svc
spec:
  ports:
    - name: rest
      port: 8000
      protocol: TCP
  selector:
    app: iris-svc
